name: lakehouse_gold
version: '1.0.0'
config-version: 2

profile: spark_lakehouse

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lakehouse_gold:
    gold:
      +materialized: table
      +file_format: delta
      +location_root: "{{ env_var('ARCH_DATA_PATH', '/data/arch1') }}/gold"
