name: lakehouse_gold
version: '1.0.0'
config-version: 2

profile: spark_lakehouse

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lakehouse_gold:
    gold:
      +materialized: table
      +file_format: delta
      +location_root: /data/arch1/gold
